version: '3'

services: 
    php:
        build: 
            context: .
            dockerfile: ./docker/php/Dockerfile
        ports:
            - 127.0.0.1:8000:80
        volumes:
            - ./:/var/www/html
    mysql:
        image: mariadb:10.5.5
        environment: 
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: tasks
            MYSQL_USER: root
            MYSQL_PASSWORD: root
        volumes:
        - ./db:/var/lib/mysql
        ports: 
            - 127.0.0.1:3306:3306